### ISSUE TITLE
[Source Request]: Perth and Kinross Council

### ISSUE THREAD

**Issue by inmcdonalds** [mampfes/hacs_waste_collection_schedule#4529]
### Municipality / Region

Perth and Kinross Council - United Kingdom

### Collection Calendar Webpage

https://my.pkc.gov.uk/AchieveForms/?mode=fill&consentMessage=yes&form_uri=sandbox-publish://AF-Process-de9223b1-a7c6-408f-aaa3-aee33fd7f7fa/AF-Stage-9fa33e2e-4c1b-4963-babf-4348ab8154bc/definition.json&process=1&process_uri=sandbox-processes://AF-Process-de9223b1-a7c6-408f-aaa3-aee33fd7f7fa&process_id=AF-Process-de9223b1-a7c6-408f-aaa3-aee33fd7f7fa

### Example Address

7 St Marys Drive, Perth, PH2 7BY

### Collection Data Format

As html on a webpage

### Additional Information

info also available as PDF or .ics

**Comment by bbr111** [comment]
Thanks for the request! I've implemented a source for Perth and Kinross Council using the council's public bin-collection lookup portal at my.pkc.gov.uk. It's been tested live against the example address from this issue (7 St Marys Drive, Perth, PH2 7BY) as well as a second address with a different bin scheme, and both return correct upcoming collection dates.

I'll open a PR shortly — once it's merged you'll be able to configure it with:

```yaml
waste_collection_schedule:
  sources:
    - name: pkc_gov_uk
      args:
        uprn: "YOUR_UPRN_HERE"
```

You can find your UPRN by using the address search on the council's bin collection page, or via https://www.findmyaddress.co.uk/.

**Comment by inmcdonalds** [comment]
Hi

Thanks for taking the time to do this. It is very much appreciated. I have
just redownloaded the integration in HACS and loaded it into HA. However,
when configuring it through the menu system, I still dont see Perth and
Kinross as an option. Is this because the pull request hasnt been merged
yet, or is it just that it has been merged but is not in the most recent
release?  Cheers.
